[package]
name = "day6"
version = "0.1.0"
authors = ["Bill Muzika <bill.muzika@outlook.com>"]
edition = "2018"

[dependencies]
trees = "0.2.1"
treeline = "0.1.0"
indextree = "4.0.0"
petgraph = "0.4.13"