[package]
name = "day7"
version = "0.1.0"
authors = ["Bill Muzika <bill.muzika@outlook.com>"]
edition = "2018"

[dependencies]
futures = { version = "0.3"}
intcode_computer_lib = { path = "../intcode_computer_lib" }